= Heyo, This is Fern!
:badge-bg: 506070
:badge-fg: F0F0F0
:badge: https://img.shields.io/static/v1?style=flat-square&color={badge-bg}&logoColor={badge-fg}&label=
:icon-sz: 20
:icon-bg: 58A6FF
:icon: https://simpleicons.now.sh

image:{badge}&message=Blender&logo=blender[Blender]
image:{badge}&message=Inkscape&logo=inkscape[Inkscape]
image:{badge}&message=Krita&logo=krita[Krita]
image:{badge}&message=ArmorPaint[ArmorPaint]
image:{badge}&message=FFMPEG&logo=ffmpeg[FFMPEG]
image:{badge}&message=ImageMagick[ImageMagick]
image:{badge}&message=Emacs&logo=gnuemacs[Emacs]
image:{badge}&message=Git&logo=git[Git] +
image:{badge}&message=C[C]
image:{badge}&message=C%2B%2B[C++]
image:{badge}&message=Scheme[Scheme]
image:{badge}&message=Python&logo=python[Python]
image:{badge}&message=Bash&logo=gnubash[Bash]
image:{badge}&message=Go&logo=go[Go]
image:{badge}&message=Kotlin&logo=kotlin[Kotlin]
image:{badge}&message=Ruby&logo=ruby[Ruby]
image:{badge}&message=Haskell&logo=haskell[Haskell]
image:{badge}&message=JavaScript&logo=javascript[JavaScript]

An artist, and more than one type of engineer.

Love making beautiful things
through a union of computing and artistry.
Because I believe that,
despite it's terrible track record,
the technology from beyond the transistor age
can be turned from a soul-devouring horror,
into a force capable of something wonderful.

== Like what I do?

Cause I know your heart is as kind as mine is humble,
I'd appreciate if you could give me a tip.
So feel free to send one on Ko-fi,
so I can keep being awesome:

image::https://ko-fi.com/img/githubbutton_sm.svg[Ko-fi, link=https://ko-fi.com/Z8Z6D2W2P]

---

ifdef::env-github[]
[subs=attributes]
++++
<a href="https://github.com/fernzi">
	<img
		src="{icon}/github/{icon-bg}"
		alt="Fern's GitHub" width="{icon-sz}" align="right">
</a>
<a href="https://gitlab.com/fernzi">
	<img
		src="{icon}/gitlab/{icon-bg}"
		alt="Fern's GitLab" width="{icon-sz}" align="right">
</a>
<a href="https://instagram.com/fernzikins/">
	<img
		src="{icon}/instagram/{icon-bg}"
		alt="Fern's Instagram" width="{icon-sz}" align="right">
</a>
<a href="https://twitter.com/fernzikins">
	<img
		src="{icon}/twitter/{icon-bg}"
		alt="Fern's Twitter" width="{icon-sz}" align="right">
</a>
++++
endif::[]

ifndef::env-github[]
[.right]
image::{icon}/github/{icon-bg}[Fern's GitHub, {icon-sz}, link=https://github.com/fernzi]

[.right]
image::{icon}/gitlab/{icon-bg}[Fern's GitLab, {icon-sz}, link=https://gitlab.com/fernzi]

[.right]
image::{icon}/instagram/{icon-bg}[Fern's Instagram, {icon-sz}, link=https://www.instagram.com/fernzikins/]

[.right]
image::{icon}/twitter/{icon-bg}[Fern's Twitter, {icon-sz}, link=https://twitter.com/fernzikins]
endif::[]

https://fern.zapata.cc[*Blog and Gallery*]
