= Heyo, This is Fern!
:color: 58A6FF
:badge: https://img.shields.io/static/v1?style=flat-square&color={color}&logoColor=FAFAFA&
:icon: https://simpleicons.now.sh
:icon-size: 20

image:{badge}label=&message=Blender&logo=blender[Blender]
image:{badge}label=&message=Inkscape&logo=inkscape[Inkscape]
image:{badge}label=&message=Krita&logo=krita[Krita]
image:{badge}label=&message=ArmorPaint[ArmorPaint]
image:{badge}label=&message=FFMPEG&logo=ffmpeg[FFMPEG]
image:{badge}label=&message=Emacs&logo=gnuemacs[Emacs]
image:{badge}label=&message=Git&logo=git[Git] +
image:{badge}label=&message=C[C]
image:{badge}label=&message=C%2B%2B[C++]
image:{badge}label=&message=Scheme[Scheme]
image:{badge}label=&message=Python&logo=python[Python]
image:{badge}label=&message=Bash&logo=gnubash[Bash]
image:{badge}label=&message=Go&logo=go[Go]
image:{badge}label=&message=Kotlin&logo=kotlin[Kotlin]
image:{badge}label=&message=Ruby&logo=ruby[Ruby]
image:{badge}label=&message=Haskell&logo=haskell[Haskell]
image:{badge}label=&message=JavaScript&logo=javascript[JavaScript]

An artist, and more than one type of engineer.

Love making beautiful things
through a union of computing and artistry.
Because I believe that,
despite it's terrible track record,
the technology from beyond the transistor age
can be turned from a soul-devouring horror,
into a force capable of something wonderful.

---

ifdef::env-github[]
[subs=attributes]
++++
<a href="https://github.com/fernzi">
	<img
		src="{icon}/github/{color}"
		alt="Fern's GitHub" width="{icon-size}" align="right">
</a>
<a href="https://gitlab.com/fernzi">
	<img
		src="{icon}/gitlab/{color}"
		alt="Fern's GitLab" width="{icon-size}" align="right">
</a>
<a href="https://instagram.com/fernzikins/">
	<img
		src="{icon}/instagram/{color}"
		alt="Fern's Instagram" width="{icon-size}" align="right">
</a>
++++
endif::[]

ifndef::env-github[]
[.right]
image::{icon}/github/{color}[Fern's GitHub, {icon-size}, link=https://github.com/fernzi]

[.right]
image::{icon}/gitlab/{color}[Fern's GitLab, {icon-size}, link=https://gitlab.com/fernzi]

[.right]
image::{icon}/instagram/{color}[Fern's Instagram, {icon-size}, link=https://www.instagram.com/fernzikins/]
endif::[]

https://fern.zapata.cc[*Blog and gallery*]
